---
- hosts: db
  sudo: yes
  roles:
     - role: geerlingguy.mysql

  tasks:
    - name: Disable iptables
      service: name=iptables state=stopped enabled=false

    - name: copy schema template
      template: src=templates/iacdb-schema.j2 dest=/tmp/iacdb-schema.sql

    - name: import database schema
      shell: mysql -u {{ mysql_iac_username }} -p{{ mysql_iac_password }} < /tmp/iacdb-schema.sql
