---
- hosts: app
  sudo: yes
  roles:
    - selinux
    - tomcat

  tasks:
    - name: Disable iptables
      service: name=iptables state=stopped enabled=false

    - name: install iac.war
      copy: src=files/iac/iac.war dest=/opt/apache-tomcat-7.0.59/webapps owner=tomcat group=tomcat mode=0755

    - name: copy platform installer
      copy: src=../platform-installer/ dest=/opt/platform-installer/ force=yes owner=tomcat group=tomcat

    - name: set permissions
      shell: chown -R tomcat:tomcat /opt/platform-installer
      shell: chmod 755 /opt/platform-installer/bin/install

    - name: run platform installer
      command: ./install -u tomcat -g tomcat -p {{ iac_platformBase }} -d {{ iac_platformDB }} -s chdir='/opt/platform-installer/bin'

    - name: set permissions
      command: chown -R tomcat:tomcat /opt/webmodules/iac

    - name: copy functional tests
      copy: src=files/iac/functional-tests/ dest=/opt/functional-tests/ force=yes owner=tomcat group=tomcat

    - name: set permissions
      shell: chown -R tomcat:tomcat /opt/functional-tests
      shell: chmod -R 755 /opt/functional-tests

    - name: restart tomcat
      command: /opt/apache-tomcat-7.0.59/bin/startup.sh
