- hosts: db
  user: root
  gather_facts: no
  connection: local
   
  tasks:
    #Call ansible module "userinfo" with parameter "username=testuser"
    - name: 'Ansible module in shell'
      action: userinfo username=vagrant
      register: userInfoVariable
    
    - name: 'Abort execution if user does not exist'
      fail: msg="User does not exist"
      when: userInfoVariable.isUserExist == False 

    - name: 'Execute task if user exist'
      #action: someaction
      shell: echo 'User exist - Replace shell with your action here.'
      register: userExist
      when: userInfoVariable.isUserExist == True
      
    - debug: var=userExist 

