VAGRANT_FILE_API_VERSION = "2"

Vagrant.configure(VAGRANT_FILE_API_VERSION) do |config|
  # Use the same key for each machine
  config.ssh.insert_key = false

  # platform server
  config.vm.define "app01" do |app01|
    app01.vm.box = "nrel/CentOS-6.5-x86_64"
	app01.vm.network "private_network", ip: "10.0.0.50"
  end

  # database server
  config.vm.define "db01" do |db01|
    db01.vm.box = "nrel/CentOS-6.5-x86_64"
	db01.vm.network "private_network", ip: "10.0.0.51"
  end

  # integration server
  config.vm.define "int01" do |int01|
    int01.vm.box = "nrel/CentOS-6.5-x86_64"
	int01.vm.network "private_network", ip: "10.0.0.52"
  end

  # configuration management server (Chef or Ansible)
  config.vm.define "cm01" do |cm01|
    cm01.vm.box = "nrel/CentOS-6.5-x86_64"
	cm01.vm.network "private_network", ip: "10.0.0.53"
  end

  # reporting server (Elastic Search)
  config.vm.define "rep01" do |rep01|
    rep01.vm.box = "nrel/CentOS-6.5-x86_64"
	rep01.vm.network "private_network", ip: "10.0.0.54"
  end
end
