#!/bin/bash

httpMethod="POST"
contentType="application/json"
apiMethod="jobcallback"
tmpFile=JobCallback.tmp
jsonFile=JobCallback.json
jsonTpl=JobCallback.json.tpl

usage() {
	echo "usage: $0 <id>"
	exit 1
}

if [ $# -ne 1 ]; then
	usage
fi

# Read IAC Configuration (iac.conf)
configFile=/opt/webmodules/iac/conf/iac.conf
source readConfig.sh
uri=${platformBase}${apiBase}/${apiMethod}

echo "curl -i -X ${httpMethod} \\"
echo "     -H \"Content-Type: ${contentType}\" \\"
echo "     -H \"Accept:${contentType}\" \\"
echo "     -d \"@${jsonFile}\" \\"
echo "     \"${uri}\" \\"

ts=`date +%s`
cat ${jsonTpl} | sed -e "s/<id>/${1}/g" > ${tmpFile}
cat ${tmpFile} | sed -e "s/<timestamp_lastRunEnd>/${ts}/g" > ${jsonFile}
curl -i -H "Content-Type: ${contentType}" -H "Accept: ${contentType}" -X ${httpMethod} -d "@${jsonFile}" "${uri}"; echo

rm -f $tmpFile

