#!/bin/bash

httpMethod="GET"
contentType="application/json"
apiMethod="cookbook"
tmpFile=${apiMethod}.tmp
jsonFile=${apiMethod}.json
jsonTpl=${apiMethod}.json.tpl

usage() {
	echo "usage: $0 [<id>] [-help|-h]"
	echo "       If no argument is given, all jobs of type ${apiMethod} will be returned."
	exit 1
}

# Read IAC Configuration (iac.conf)
configFile=/opt/webmodules/iac/conf/iac.conf
source readConfig.sh

# configure URI
if [ $# -eq 0 ]; then
	uri=${platformBase}${apiBase}/${apiMethod}
elif [ $# -eq 1 ]; then
	case ${1} in
	"-h")
		usage ;;
	"-help")
		usage ;;
	*)
		uri=${platformBase}${apiBase}/${apiMethod}/${1}
	esac
else
	usage
fi

echo "curl -i -X ${httpMethod} \\"
echo "     -H \"Content-Type: ${contentType}\" \\"
echo "     -H \"Accept: ${contentType}\" \\"
echo "     \"${uri}\""

curl -i -H "Content-Type: ${contentType}" -H "Accept: ${contentType}" -X ${httpMethod} "${uri}"; echo
