---
# create an organization in Raindance IAC

- hosts: localhost

  tasks:
    - name: init
      set_fact:
        cm_api: "http://10.234.3.135"

    - name: create IAC organization
      iac_org:
        name: "cm-core"
        state: present
        cm_api: "{{cm_api}}"
        fullName: "Cloud Manager Organization"
        vSpheres:
          host: "10.234.0.4"
          user: "admin"
          password: "uDZ9UxOxtvw4o107"

    - name: delete IAC organization
      iac_org:
        name: "cm-core"
        state: absent
        cm_api: "{{cm_api}}"
